# Generated by Django 3.2.8 on 2022-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='remarks',
            field=models.CharField(default='No-Remark', max_length=255),
        ),
    ]
