# Generated by Django 3.2.8 on 2021-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='author_files/'),
        ),
    ]
