# Generated by Django 3.2.8 on 2021-12-27 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_paper_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='assign_paper',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_reg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assign_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paper')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.review')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
