# Generated by Django 3.2.8 on 2022-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220102_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
