# Generated by Django 3.2.8 on 2021-12-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211227_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignPaper',
            new_name='PaperAssign',
        ),
    ]
