# Generated by Django 3.2.8 on 2022-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paper_is_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='is_review',
        ),
        migrations.AddField(
            model_name='paper',
            name='review_by',
            field=models.IntegerField(default=0),
        ),
    ]
