# Generated by Django 3.2.8 on 2022-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paper_is_review_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
