# Generated by Django 3.2.3 on 2021-12-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='paperassign',
            name='assign_paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paperassign', to='core.paper'),
        ),
    ]
