# Generated by Django 3.2.3 on 2021-12-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211228_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperassign',
            name='assign_paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_assign', to='core.paper'),
        ),
    ]
