# Generated by Django 3.2.8 on 2022-01-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_updated_on_paper_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
