# Generated by Django 3.2.8 on 2021-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paperassign_assign_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(default='Submitted', max_length=30),
        ),
    ]
