# Generated by Django 3.2.8 on 2022-01-10 07:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220107_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='author_files/', validators=[core.validators.validate_is_pdf]),
        ),
    ]
