# Generated by Django 3.2.8 on 2022-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paper_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='review_by',
            field=models.IntegerField(null=True),
        ),
    ]
