# Generated by Django 3.2.8 on 2021-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_paper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
