# Generated by Django 3.2.8 on 2021-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_paper_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
