# Generated by Django 3.2.8 on 2021-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_paper_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperassign',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
